FEAT: Add simple evaluation functions
Thomaltarix/Gomoku pull request #11
Opened 2024-11-13 15:29 UTC by AubaneNourry

Simple evaluation functions for 20x20 Gomoku boards.
Will probably change to consider other indicators like:
- Mobility Score (Positional Advantage)
- Weighted Threat Assessment
In other set of functions.

See : 
- #10 for more informations.

2024-11-13 15:40 UTC, Peralban requested changes

2024-11-13 15:40 UTC, Peralban commented on evaluation.py
> +    diags = get_diagonals(board)
Types

2024-11-13 15:40 UTC, Peralban commented on evaluation.py
> +    line_score = 0
Same

2024-11-13 15:40 UTC, Peralban commented on evaluation.py
> +    i = 0
Same

2024-11-13 15:40 UTC, Peralban commented on evaluation.py
> +            count, open_ends = 0, 0
elif
else ?

2024-11-13 15:40 UTC, Peralban commented on evaluation.py
> +    diags = []
Types

2024-11-13 15:40 UTC, Peralban commented on evaluation.py
> +        diag1, diag2 = [], []
Types

2024-11-13 15:40 UTC, Peralban commented on evaluation.py
> +    score = 0
Same

2024-11-13 15:40 UTC, Peralban commented on evaluation.py
> +    opponent = -player
Same

2024-11-13 15:48 UTC, Thomaltarix requested changes
Seems fair

2024-11-13 15:48 UTC, Thomaltarix commented on evaluation.py
> +def evaluate_pattern_based(board: list, player: int = 1) -> int:
You can a comment the function 😉

2024-11-13 15:48 UTC, Thomaltarix commented on evaluation.py
> +def evaluate_line_of_sight_with_opponent(board: list, player: int = 1) -> int:
You can comment this one too

2024-11-14 16:32 UTC, AubaneNourry commented on evaluation.py
> +def evaluate_line_of_sight_with_opponent(board: list, player: int = 1) -> int:
why? these two are the most accurate since line of sight does not count the opponent pieces in the returned value?

2024-11-14 16:45 UTC, Thomaltarix commented on evaluation.py
> +def evaluate_line_of_sight_with_opponent(board: list, player: int = 1) -> int:
The main reason is to know what are the parameters that you need to send. For example, the board is a list, so it's obvious. But for the player, without reading the code, how do you know what you're supposed to send as parameter for the player ? (And what means the 1 that is by default ?)

2024-11-14 16:45 UTC, Peralban submitted a review, later dismissed

2024-11-14 16:51 UTC, Thomaltarix submitted a review, later dismissed
I'll let you just add the documentation, but that's great

2024-11-14 16:56 UTC, Thomaltarix approved these changes

2024-11-14 16:57 UTC, merged